/*
Assumptions:
    - Data warehouse already exists
    - Database "SPOTIFY_PIPELINE" and schemas, "RAW", "TRANSFORMED" and "METADATA"
    from setup.sql already exist
    - This file is run with role SYSADMIN/SECURITYADMIN
*/
CREATE ROLE IF NOT EXISTS SPOTIFY_PIPELINE_ROLE;

GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE SPOTIFY_PIPELINE_ROLE;
GRANT USAGE ON DATABASE SPOTIFY_PIPELINE TO ROLE SPOTIFY_PIPELINE_ROLE;

GRANT USAGE ON SCHEMA SPOTIFY_PIPELINE.RAW TO ROLE SPOTIFY_PIPELINE_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SPOTIFY_PIPELINE.RAW TO ROLE SPOTIFY_PIPELINE_ROLE;
GRANT INSERT ON FUTURE TABLES IN SCHEMA SPOTIFY_PIPELINE.RAW TO ROLE SPOTIFY_PIPELINE_ROLE;


GRANT USAGE ON SCHEMA SPOTIFY_PIPELINE.TRANSFORMED TO ROLE SPOTIFY_PIPELINE_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SPOTIFY_PIPELINE.TRANSFORMED TO ROLE SPOTIFY_PIPELINE_ROLE;

GRANT USAGE ON SCHEMA SPOTIFY_PIPELINE.METADATA TO ROLE SPOTIFY_PIPELINE_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SPOTIFY_PIPELINE.METADATA TO ROLE SPOTIFY_PIPELINE_ROLE;
GRANT INSERT ON FUTURE TABLES IN SCHEMA SPOTIFY_PIPELINE.METADATA TO ROLE SPOTIFY_PIPELINE_ROLE;


GRANT ROLE SPOTIFY_PIPELINE_ROLE TO USER ishanb30;
