
CREATE DATABASE IF NOT EXISTS SPOTIFY_PIPELINE;

CREATE SCHEMA IF NOT EXISTS SPOTIFY_PIPELINE.RAW;
CREATE SCHEMA IF NOT EXISTS SPOTIFY_PIPELINE.STAGING;
CREATE SCHEMA IF NOT EXISTS SPOTIFY_PIPELINE.INTERMEDIATE;
CREATE SCHEMA IF NOT EXISTS SPOTIFY_PIPELINE.MART;

CREATE TABLE IF NOT EXISTS SPOTIFY_PIPELINE.RAW.RECENTLY_PLAYED(
    RUN_ID VARCHAR(36),
    RAW_DATA VARIANT,
    LOADED_AT TIMESTAMP_NTZ DEFAULT SYSDATE()
);

CREATE TABLE IF NOT EXISTS SPOTIFY_PIPELINE.RAW.PIPELINE_RUNS(
    RUN_ID VARCHAR(36) PRIMARY KEY,
    RUN_START TIMESTAMP_TZ,
    RUN_END TIMESTAMP_TZ,
    WATERMARK_TIMESTAMP TIMESTAMP_TZ,
    RUN_STATUS VARCHAR(9)
);



