
CREATE DATABASE IF NOT EXISTS SPOTIFY_PIPELINE;

CREATE SCHEMA IF NOT EXISTS SPOTIFY_PIPELINE.RAW;
CREATE SCHEMA IF NOT EXISTS SPOTIFY_PIPELINE.TRANSFORMED;
CREATE SCHEMA IF NOT EXISTS SPOTIFY_PIPELINE.METADATA;

CREATE STAGE IF NOT EXISTS SPOTIFY_PIPELINE.RAW.RAW_STAGE;
CREATE FILE FORMAT IF NOT EXISTS SPOTIFY_PIPELINE.RAW.JSON_FORMAT TYPE = 'JSON';

CREATE TABLE IF NOT EXISTS SPOTIFY_PIPELINE.RAW.RECENTLY_PLAYED(
    RAW_DATA VARIANT,
    LOADED_AT TIMESTAMP_NTZ
)



