
CREATE DATABASE IF NOT EXISTS SPOTIFY_PIPELINE;

CREATE SCHEMA IF NOT EXISTS SPOTIFY_PIPELINE.RAW;
CREATE SCHEMA IF NOT EXISTS SPOTIFY_PIPELINE.STAGING;
CREATE SCHEMA IF NOT EXISTS SPOTIFY_PIPELINE.INTERMEDIATE;
CREATE SCHEMA IF NOT EXISTS SPOTIFY_PIPELINE.MART;
CREATE SCHEMA IF NOT EXISTS SPOTIFY_PIPELINE.METADATA;

CREATE TABLE IF NOT EXISTS SPOTIFY_PIPELINE.RAW.RECENTLY_PLAYED(
    RAW_DATA VARIANT,
    LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);



