
name: 'transform'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'transform'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  transform:
    staging:
      +materialized: view
      +schema: STAGING

    intermediate:
      +materialized: view
      +schema: INTERMEDIATE

    mart:
      +materialized: table
      +schema: MART
